# Generated by Django 3.1.6 on 2021-09-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
    ]
