# Generated by Django 3.1.6 on 2021-09-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_remove_image_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
