# Generated by Django 3.1.6 on 2021-09-17 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detect', '0003_image_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
